# Generated by Django 3.1 on 2020-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_num', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='Bus_Station',
            fields=[
                ('bus_station_num', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('bus_station_name', models.CharField(max_length=30, null=True)),
                ('bus_list', models.ManyToManyField(blank=True, to='api.Bus')),
            ],
            options={
                'db_table': 'Bus_Station',
            },
        ),
    ]
