# Generated by Django 3.1 on 2020-08-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_num',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
