# Generated by Django 3.1 on 2020-08-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200827_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_station',
            name='bus_list',
            field=models.ManyToManyField(to='api.Bus'),
        ),
    ]
