# Generated by Django 3.1 on 2020-09-01 07:30

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200901_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected_List',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('selected_list', django_mysql.models.ListCharField(models.IntegerField(), max_length=12, size=None)),
            ],
            options={
                'db_table': 'Selected_List',
            },
        ),
    ]
