# Generated by Django 3.1 on 2020-09-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_selected_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_list',
            name='selected_list',
        ),
        migrations.AddField(
            model_name='selected_list',
            name='selected_list',
            field=models.ManyToManyField(to='api.Bus'),
        ),
    ]
